export const darkGray = '#BBB'
export const gray = '#DFDFDF'
export const lightPurp = '#7C53C3'
export const purple = '#9090E0'
export const orange = '#F22f28'
export const red = '#990010'
export const textGray = '#777'
export const white = '#EEE'
